#!/bin/bash

# Deploy Rook Backend to AWS using SAM
# This script builds and deploys the backend infrastructure

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/backend"

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║            🚀 ROOK BACKEND AWS DEPLOYMENT                  ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check prerequisites
echo -e "${BLUE}Checking prerequisites...${NC}"

if ! command -v aws &> /dev/null; then
    echo -e "${RED}❌ AWS CLI is not installed. Please install AWS CLI first.${NC}"
    exit 1
fi

if ! command -v sam &> /dev/null; then
    echo -e "${RED}❌ SAM CLI is not installed. Please install SAM CLI first.${NC}"
    echo -e "${YELLOW}   Install: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html${NC}"
    exit 1
fi

if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js is not installed. Please install Node.js 18+.${NC}"
    exit 1
fi

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}❌ AWS credentials not configured. Please run 'aws configure'.${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Prerequisites check passed${NC}"
echo ""

# Navigate to backend directory
cd "$BACKEND_DIR"

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo -e "${BLUE}Installing backend dependencies...${NC}"
    npm install
else
    echo -e "${GREEN}✓ Dependencies already installed${NC}"
fi

# Build SAM application
echo -e "${BLUE}Building SAM application...${NC}"
sam build

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ SAM build failed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ SAM build successful${NC}"
echo ""

# Check if this is first deployment
if [ ! -f "samconfig.toml" ]; then
    echo -e "${YELLOW}First deployment detected. Running guided deployment...${NC}"
    echo -e "${YELLOW}You will be prompted for stack name, region, and other parameters.${NC}"
    echo ""
    sam deploy --guided
else
    echo -e "${BLUE}Deploying to AWS...${NC}"
    sam deploy
fi

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Deployment failed${NC}"
    exit 1
fi

# Get stack outputs
echo ""
echo -e "${BLUE}Retrieving deployment outputs...${NC}"

STACK_NAME=$(grep -A 1 "^stack_name" samconfig.toml 2>/dev/null | tail -1 | sed 's/.*= *"\(.*\)".*/\1/' || echo "rook-game")
REGION=$(grep -A 1 "^region" samconfig.toml 2>/dev/null | tail -1 | sed 's/.*= *"\(.*\)".*/\1/' || echo "us-east-1")

HTTP_API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`HttpApiUrl`].OutputValue' \
    --output text 2>/dev/null || echo "")

WS_API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`WebSocketApiUrl`].OutputValue' \
    --output text 2>/dev/null || echo "")

# Save URLs to file for frontend deployment
ENV_FILE="$SCRIPT_DIR/.deployment-env"
cat > "$ENV_FILE" << EOF
# Deployment URLs - Generated by deploy-backend.sh
# Do not edit manually

REACT_APP_API_BASE_URL=$HTTP_API_URL
REACT_APP_WS_BASE_URL=$WS_API_URL
STACK_NAME=$STACK_NAME
REGION=$REGION
EOF

echo ""
echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║              ✅ BACKEND DEPLOYMENT COMPLETE                ║"
echo "╠═══════════════════════════════════════════════════════════╣"
echo "║                                                           ║"
if [ -n "$HTTP_API_URL" ]; then
    echo "║   HTTP API URL:    $HTTP_API_URL"
fi
if [ -n "$WS_API_URL" ]; then
    echo "║   WebSocket URL:   $WS_API_URL"
fi
echo "║                                                           ║"
echo "║   URLs saved to: .deployment-env                          ║"
echo "║   Use these URLs when deploying the frontend              ║"
echo "║                                                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
